# Generated by Django 4.2.3 on 2023-07-14 12:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("FIO", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=12, validators=[users.models.validate_phone]
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        max_length=8, validators=[users.models.validate_group]
                    ),
                ),
            ],
        ),
    ]
