# Generated by Django 4.2.3 on 2023-07-14 15:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                max_length=24, validators=[users.models.validate_phone]
            ),
        ),
    ]
