# Generated by Django 4.2.3 on 2023-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="names_of_priority",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
