# Generated by Django 4.2.3 on 2023-07-17 14:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_student_telegram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="telegram",
            field=models.CharField(
                max_length=20, validators=[users.models.validate_telegram]
            ),
        ),
    ]
