# Generated by Django 4.2.3 on 2023-07-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holidays", "0001_initial"),
        ("users", "0016_remove_booking_id_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holidays.destinations",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.student",
                unique=True,
            ),
        ),
    ]
