# Generated by Django 4.2.3 on 2023-07-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_booking_destination_alter_booking_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.student",
            ),
        ),
    ]
