# Generated by Django 4.2.3 on 2023-07-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holidays", "0001_initial"),
        ("users", "0018_alter_booking_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holidays.destinations",
            ),
        ),
    ]
