# Generated by Django 4.2.3 on 2023-07-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="FIO",
            field=models.CharField(max_length=100),
        ),
    ]
