# Generated by Django 4.2.3 on 2023-07-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_student_fio_alter_student_email"),
        ("users", "0021_alter_student_fio"),
    ]

    operations = []
