# Generated by Django 4.2.3 on 2023-07-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_merge_20230719_1603"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="names_of_priority",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
